parent/urls.py
"""Defines the url patterns for the parents app
    """

from django.urls import path
from . import views


#url conf
app_name = 'parent'

urlpatterns = [
    
    path('parent-registration/',views.parent_registration ,name='parent-registration'),
    path('profile/<str:parent_name>',views.parent_profile ,name='parent-profile'),
    path('parent-list/',views.parent_list ,name='parent-list'),
    path('edit/<str:parent_name>',views.parent_edit , name ='parent-edit'),
    path('delete/<str:parent_name>',views.parent_delete , name ='parent-delete'),

]

schoolmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_page
from schoolmanagementsystem import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name = 'home'), #home page
    path('',include('administration.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('parent/',include('parent.urls'))
    
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student/urls.py
"""Defines the url patterns for the students app
    """

from django.urls import path
from . import views


#url conf
app_name = 'student'

urlpatterns = [
    
    path('student-registration/',views.student_registration ,name='student-registration'),
    path('profile/<reg_no>',views.student_profile ,name='student-profile'),
    path('student-list/',views.student_list ,name='student-list'),
    path('edit/<reg_no>',views.student_edit , name ='student-edit'),
    path('delete/<int:reg_no>',views.student_delete , name ='student-delete'),
    path('student-search/', views.student_search, name='student-search'), 
    path('enrolled/', views.enrolled_student, name ='student-enrolled'),
    path('enrolled-student/<reg>',views.student_enrolled, name='enrolled' ),
    path('enrolled-student-list/',views.enrolled_student_list, name ='enrolled-student-list'),

]

student/models.py
from django.db import models
import random

from academic.models import ClassInfo ,ClassRegistration


# Create your models here.
class PersonalInfo(models.Model):
    """Returns the personal information about a student

    Args:
        models ([type]): [description]

    Returns:
        [type]: [description]
    """
    name = models.CharField(max_length = 100)
    photo = models.ImageField(upload_to = 'student-photos/',blank = True ,null=True)
    date_of_birth = models.DateField()
    gender_choices =(
        ('male','Male'),
        ('female','Female'),
        ('other','Other')
        
    )
    gender = models.CharField(choices = gender_choices,max_length=10)
    phone_no = models.CharField(max_length = 10)
    email = models.EmailField(blank = True)
    religion_choice =(
        ('christian','Christian'),
        ('muslim','Muslim'),
        ('other','Other'),
    )
    religion = models.CharField(choices = religion_choice,max_length = 50)
    birth_certificate_no = models.IntegerField(default=000000)

    def __str__(self):
        
        """Return a string representation of a student's name

        Returns:
            [type] -- [description]
        """
        return self.name
    @property
    def get_photo_url(self):
        if self.photo and hasattr(self.photo ,'url'):
            return self.photo.url    
       

    class Meta:
        verbose_name_plural = 'Personal Information'


class AcademicInfo(models.Model):
    """Provides the academic information about a student

    Arguments:
        models {[type]} -- [description]

    Returns:
        [type] -- [description]
    """
    class_info = models.ForeignKey(ClassInfo , on_delete=models.CASCADE)
    registration_no = models.IntegerField(unique=True,default = random.randint(000000,999999))
    personalInfo = models.ForeignKey(PersonalInfo, on_delete= models.CASCADE ,null = True,max_length =6)
    is_delete = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)
    status_select =(
        ('enrolled','Enrolled'),
        ('not enrolled','Not Enrolled')
    )
    status = models.CharField(max_length = 20 ,choices = status_select, default ='Not Enrolled')

    def __str__(self):
        """Returns a student's academic info
        Returns:
            [type] -- [description]
        """
        return str(self.registration_no)

    class Meta():
        verbose_name_plural = 'Academic Information'

class EnrolledStudent(models.Model):
    """Shows a list of all the enrolled students in the system

    Arguments:
        models {[type]} -- [description]
    """
    class_name = models.ForeignKey(ClassRegistration,on_delete=models.CASCADE)
    student = models.OneToOneField(AcademicInfo,on_delete=models.CASCADE)
    roll = models.IntegerField(default = 000000)
    date = models.DateField(auto_now_add=True)
    class Meta:
        unique_together = ['class_name','roll']
    
    def __str__(self):
        return str(self.roll)
    

student/forms.py
from django import forms
from .models import *
from academic.models import ClassInfo



class PersonalInfoForm(forms.ModelForm):
    class Meta:
        model = PersonalInfo
        fields = '__all__'
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'photo' : forms.ClearableFileInput(attrs={'class':'form-control'}),
            'gender' : forms.Select(attrs={'class':'form-control'}),
            'phone_no' : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.TextInput(attrs={'class':'form-control'}),
            'religion' : forms.Select(attrs={'class':'form-control'}),
            'birth_certficate_no' : forms.TextInput(attrs={'class':'form-control'}),

        }

class AcademicInfoForm(forms.ModelForm):
    class Meta:
        model = AcademicInfo
        exclude = ['date','status','is_delete']
        widgets = {
            'class_info': forms.Select(attrs={'class':'form-control'}),
            
        }

class EnrolledStudentForm(forms.Form):
    class_name = forms.ModelChoiceField(queryset=ClassInfo.objects.all())




class StudentEnrollForm(forms.Form):
    class_name = forms.ModelChoiceField(queryset=ClassRegistration.objects.all())
    roll_no = forms.IntegerField(widget=forms.NumberInput(attrs={'placeholder':'Enter roll','class':'form-control'}))


class SearchEnrolledStudentForm(forms.Form):
    reg_class = forms.ModelChoiceField(queryset=ClassRegistration.objects.all())
    roll_no = forms.IntegerField(required= False,widget=forms.NumberInput(attrs={'placeholder':'Enter Roll:'}))    

class StudentSearchForm(forms.Form):
    class_info = forms.ModelChoiceField(required=False, queryset=ClassInfo.objects.all())
    registration_no = forms.IntegerField(required=False, widget=forms.NumberInput(attrs={'placeholder': 'Registration No', 'aria-controls': 'DataTables_Table_0'}))  

student/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from academic.models import ClassInfo
from .forms import *

# Create your views here.

def student_registration(request):
    """A student registration form that is sent back to the database when it is valid

    Args:
        request ([type]): [description]

    Returns:
        [type]: [description]
    """
    personal_info_form = PersonalInfoForm(request.POST)
    academic_info_form = AcademicInfoForm(request.POST)


    if request.method == 'POST':

        if personal_info_form.is_valid() and academic_info_form.is_valid():
            s1=personal_info_form.save()
            s2=academic_info_form.save()
            academic_info = academic_info_form.save(commit=False)
            academic_info.personalInfo = s1
            academic_info.save()

            return redirect('student:student-list')

    context ={
        'personal_info_form':personal_info_form,
        'academic_info_form':academic_info_form
    }
    
    return render(request , 'student/student_registration.html',context)

def student_profile(request,reg_no):
    """Returns a student to their profile page

    Args:
        request ([type]): [description]
        reg_no ([type]): [description]

    Returns:
        [type]: [description]
    """
    student = AcademicInfo.objects.get(registration_no = reg_no)
    context = {'student':student}
    return render(request,'student/student-profile.html',context)



def student_list(request):
    """Shows the whole list of students

    Args:
        request ([type]): [description]

    Returns:
        [type]: [description]
    """
    students = AcademicInfo.objects.filter(is_delete=False).order_by('-id')
    context ={'students':students }
    return render(request,'student/student_list.html',context)



def student_edit(request,reg_no):
    """Edit's the student registration form and redirects them to the student list page

    Args:
        request ([type]): [description]
        reg_no ([type]): [description]

    Returns:
        [type]: [description]
    """
#GET METHOD = BLANK FORM
    student = AcademicInfo.objects.get(registration_no=reg_no)
    personal_info_form = PersonalInfoForm(instance=student.personalInfo)
    academic_info_form = AcademicInfoForm(instance=student)

#POST METHOD = FILL IT WITH DATA
    if request.method == 'POST':
        personal_info_form = PersonalInfoForm(request.POST,request.FILES,instance=student.personalInfo)
        academic_info_form = AcademicInfoForm(request.POST,request.FILES,instance=student)

        if personal_info_form.is_valid() and academic_info_form.is_valid():
            s1=personal_info_form.save()
            s2=academic_info_form.save()
            academic_info = academic_info_form.save(commit=False)
            academic_info.personalInfo = s1
            academic_info.save()

            return redirect('student:student-list')
            
    context ={
        'personal_info_form':personal_info_form,
        'academic_info_form':academic_info_form
    }
    
    return render(request,'student/student-edit.html',context)




def student_delete(request,reg_no):
    """Deletes a student 

    Args:
        request ([type]): [description]
        reg_no ([type]): [description]

    Returns:
        [type]: [description]
    """
    student = AcademicInfo.objects.get(registration_no = reg_no)
    student.is_delete = True
    student.save()
    return redirect('student:student-list')



def enrolled_student(request):
    forms = EnrolledStudentForm()
    class_name =request.GET.get('class_name',None)
    student = AcademicInfo.objects.filter(class_info = class_name, status='not enrolled')
    context = {
        'forms': forms,
        'student':student,
    }
    
    return render(request,'student/enrolled.html',context)



def student_enrolled(request, reg):
    """Enrolls a student into the system trough a StudentEnrollForm

    Args:
        request ([type]): [description]
        reg_no ([type]): [description]

    Returns:
        [type]: [description]
    """
    student = AcademicInfo.objects.get(registration_no = reg)
    forms = StudentEnrollForm()
    if request.method == 'POST':
        forms = StudentEnrollForm(request.POST)
        if forms.is_valid():
            roll = forms.cleaned_data['roll_no']
            class_name =forms.cleaned_data['class_name']
            EnrolledStudent.objects.create(class_name=class_name,student=student,roll=roll)
            student.status = 'enrolled'
            student.save()
            return redirect('student:enrolled-student-list')

    context = {
       
        'student':student,
         'forms': forms
    }
    return render(request,'student/student-enrolled.html',context)





def enrolled_student_list(request):
    student = EnrolledStudent.objects.all()
    forms = SearchEnrolledStudentForm()
    class_name = request.GET.get('reg_class',None)
    roll = request.GET.get('roll_no',None)
    if class_name:
        student = EnrolledStudent.objects.filter(class_name=class_name)
        context = {
            'forms': forms,
            'student': student
        }
        return render(request, 'student/enrolled-student-list.html',context)
    context ={
        'forms':forms,
        'student': student
    }


def student_search(request):
    forms = StudentSearchForm()
    cls_name = request.GET.get('class_info', None)
    reg_no = request.GET.get('registration_no', None)
    if cls_name:
        student = AcademicInfo.objects.filter(class_info=cls_name)
        if reg_no:
            student = student.filter(registration_no=reg_no)
        context = {
            'forms': forms,
            'student': student
        }
        return render(request, 'student/student-search.html', context)
    else:
        student = AcademicInfo.objects.filter(registration_no=reg_no)
        context = {
            'forms': forms,
            'student': student
        }
        return render(request, 'student/student-search.html', context)
    context = {
            'forms': forms,
            'student': student
        }
    return render(request, 'student/student-search.html', context)

   

    return render(request,'student/enrolled-student-list.html',context)

templates/student/enrolled-student-list.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Student Tables</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Registration number</th>
                <th>Roll</th>
                <th>Class</th>
                <th>Enrollment Date</th>
                <th>Actions</th>
      
              </tr>
            </thead>
            <tbody>
              {%for student in student%}
              <tr role="row" >
                
                <td>{{forloop.counter}}</td>
                <td>{{student.student.personalInfo.name}}</td>
                <td>{{student.student.registration_no}}</td>
                <td>{{student.roll}}</td>
                <td>{{student.class_name}}</td>
                <td>{{student.date}}</td>
                <td>
                  <button class="btn btn-info">
                    <a href="{%url 'student:student-profile' student.student.registration_no%}">
                    </a> Profile
                  </button>
                  <button class="btn btn-success">
                    <a href="{%url 'student:student-edit' student.student.registration_no %}">
                      <i class="fa fa-edit"></i>
                    </a> Edit
                  </button>
                <button class="btn btn-danger">
                  <a href="{%url 'student:student-delete' student.student.registration_no %}" >
                    <i class="fa fa-trash-o"></i>
                    </a>
                    Delete
                  </button>
                </td>
              </tr>
              
                {%endfor%}
    
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-5">
      </div>
      <div class="col-sm-12 col-md-7">
        <div class="pagination">
          <ul class="pagination">
          <li class="paginate_button page-item previous disabled" ><a href="#" class="page-link">Previous</a></li>
          <li class="paginate_button page-item" ><a href="#" class="page-link">1</a></li>
          <li class="paginate_button page-item" ><a href="#" class="page-link">2</a></li>
          <li class="paginate_button page-item" ><a href="#" class="page-link">3</a></li>
        </ul>
      </div>
      </div>
    </div>
  </div>
  <!-- /.row -->
{%endblock%}

templates/student/student-edit.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<h2>Student Registration Form</h2>
<!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Personal Information</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="" enctype="multipart/form-data">
              <div class="card-body">
                {% csrf_token %}
                {{ personal_info_form.as_p }}
                
              </div>
              <div class="card card-primary">
                
              <div class="card-header">
                <h3 class="card-title">Academic Information</h3>
              </div>
              <div class="card-body">
                {% csrf_token %}
                {{ academic_info_form.as_p }}
                
              </div>
              
                
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Save Student</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
  
{%endblock%}

templates/student/student-enrolled.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<div class="card">
        
    
    <div class="card-body">
        <div class="row">
            <h2 class="mx-auto">Academic Information</h2>
        </div>
        <hr>
        <div style="font-size: 24px; margin-left: 30px;">
    <pre>Class:                                  {{student.class_info|title}}</pre>
    <pre>Registration Number:                    {{student.registration_no}} </pre>
    <pre>Status:                                 {{student.status}}</pre>
    <pre>Date Registered:                        {{student.date}}</pre>
        
        </div>
        <div class="card">
            <div class="row">
                <div class="card-body">
        <form action="" method="POST">

            {% csrf_token %}
            {{ forms.as_p }}
            
            <input type="submit" value="Enroll" class="btn btn-primary">
        </form>
        </div>
    </div>
    </div>

    </div>
</div>

{%endblock%}

templates/student/student-profile.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
  <div class="card">
    
    <div class="card-header">
      <div class="row">
        {%if student.personalInfo.photo %}
        <img style="height:200px; width:200px; border-radius:50%; margin:auto ;background-size:cover"  src="{{ student.personalInfo.get_photo_url }}" alt="Photo">
      {% else %}
      <img style="height:200px; width:200px; border-radius:50%; margin:auto ;background-size:cover"  src="{%static 'images/default.jpg'%}" alt="Photo">
        {% endif %}
      </div>
    </div>
    
    <div class="card-body">

      <div class="personal_information">
        <div class="row">
          <h2 class="mx-auto">Personal Information</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Name                        :  {{student.personalInfo.name}}</pre>
            <pre>Date of birth               :  {{student.personalInfo.date_of_birth}} </pre>
            <pre>Gender                      :  {{student.personalInfo.gender}}</pre>
            <pre>Phone number                :  {{student.personalInfo.phone_no}}</pre>
            <pre>Email                       :  {{student.personalInfo.email}}</pre>
            <pre>Religion                    :  {{student.personalInfo.religion}}</pre>
            <pre>Birth Certificate Number    :  {{student.personalInfo.birth_certificate_no}}</pre>
          </div>
        </div>
      </div>

      

      

      <div class="emergency_contact_information">
        <div class="row">
          <h2 class="mx-auto">Academic Information</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Class                       :  {{student.class_info}}</pre>
            <pre>Registration number         :  {{student.registration_no}}</pre>
            
          </div>
        </div>
      </div>
      
    </div>
  </div>
{% endblock %}

templates/student/student_list.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Student Tables</h3>
          {%if students%}
          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div><div class="col-sm-12 col-md-6">
          <div id="DataTables_Table_0_filter" class="dataTables_filter">
              <form action="" method="GET">
                  {% csrf_token %}
                <label>Search:
                    <!-- <input type="search" class="form-control form-control-sm" placeholder="" aria-controls="DataTables_Table_0"> -->
                    {{ search.registration_no }}
                </label>
              </form>
          </div>
      </div>
  </div>
        <!-- /.card-header -->
        
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Registration number</th>
                <th>Class</th>
                <th>Date</th>
      
              </tr>
            </thead>
            <tbody>
              {%for student in students%}
              <tr role="row" >
                
                <td>{{forloop.counter}}</td>
                <td>{{student.personalInfo.name}}</td>
                <td>{{student.registration_no}}</td>
                <td>{{student.class_info}}</td>
                <td>{{student.date}}</td>
                <td>
                 
                  <a class="btn btn-info" href="{% url 'student:student-profile' student.registration_no %}">
                    <i class="fa fa-search-plus"></i>
                </a>
                 
                  
                    <a class="btn btn-success" href="{%url 'student:student-edit' student.registration_no %}">
                      <i class="fa fa-edit"></i> </a>
                    
                 
                
                  <a class="btn btn-danger" href="{%url 'student:student-delete' student.registration_no %}" >
                    <i class="fa fa-trash"></i>
                    </a>
                </td>
              </tr>
              
                {%endfor%}
    
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    {%else%}
    <div class="card-body">
      <h2>No Student Found</h2>
    </div>
    {%endif%}
  </div>
  <!-- /.row -->
{%endblock%}

templates/student/student_registration.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<h2>Student Registration Form</h2>
<!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Personal Information</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{%url 'student:student-registration'%}"enctype="multipart/form-data">
              <div class="card-body">
                {% csrf_token %}
                {{ personal_info_form.as_p }}
                
              </div>
              <div class="card card-primary">
                
              <div class="card-header">
                <h3 class="card-title">Academic Information</h3>
              </div>
              <div class="card-body">
                {% csrf_token %}
                {{ academic_info_form.as_p }}
                
              </div>
              
                
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
  

{%endblock%}