academic/urls.py
from django.urls import path
from . import views

app_name = 'academic'

urlpatterns = [
    path('class-registration/', views.class_registration, name="class-registration"),
    path('create-class/', views.add_class, name="create-class"),
    path('class-list/', views.class_list, name='class-list'),
    

    

]

parent/urls.py
"""Defines the url patterns for the parents app
    """

from django.urls import path
from . import views


#url conf
app_name = 'parent'

urlpatterns = [
    
    path('parent-registration/',views.parent_registration ,name='parent-registration'),
    path('profile/<str:parent_name>',views.parent_profile ,name='parent-profile'),
    path('parent-list/',views.parent_list ,name='parent-list'),
    path('edit/<str:parent_name>',views.parent_edit , name ='parent-edit'),
    path('delete/<str:parent_name>',views.parent_delete , name ='parent-delete'),

]

schoolmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_page
from schoolmanagementsystem import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name = 'home'), #home page
    path('',include('administration.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('parent/',include('parent.urls'))
    
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

student/urls.py
"""Defines the url patterns for the students app
    """

from django.urls import path
from . import views


#url conf
app_name = 'student'

urlpatterns = [
    
    path('student-registration/',views.student_registration ,name='student-registration'),
    path('profile/<reg_no>',views.student_profile ,name='student-profile'),
    path('student-list/',views.student_list ,name='student-list'),
    path('edit/<reg_no>',views.student_edit , name ='student-edit'),
    path('delete/<int:reg_no>',views.student_delete , name ='student-delete'),
    path('student-search/', views.student_search, name='student-search'), 
    path('enrolled/', views.enrolled_student, name ='student-enrolled'),
    path('enrolled-student/<reg>',views.student_enrolled, name='enrolled' ),
    path('enrolled-student-list/',views.enrolled_student_list, name ='enrolled-student-list'),

]

teacher/urls.py
from django.urls import path

from . import views
app_name = 'teacher'

urlpatterns = [
    path('registration', views.teacher_registration, name='teacher-registration'),
    path('list', views.teacher_list, name='teacher-list'),
    path('profile/<teacher_id>', views.teacher_profile, name='teacher-profile'),
    path('delete/<teacher_id>', views.teacher_delete, name='teacher-delete'),
    path('edit/<teacher_id>', views.teacher_edit, name='teacher-edit'),
]

templates/base/base.html
<!DOCTYPE html>
<html lang="en">
<!--Headers-->
{%include 'base/header.html'%}
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
    <!--Navbar-->
    {%include 'base/navbar.html'%}

        <!--Sidebar-->
        {%include 'base/sidebar.html'%}

            <main class="main">
            <!--Breadcrumb-->
            {%include 'base/breadcrumb.html'%}

                <!--Page contents-->

                {%block content%}
                {%endblock%}
            </main>
    </div>
<!--Footer-->
{%include 'base/footer.html'%}

<!--Javascript-->
{%include 'base/js.html'%}
    
</body>
</html>

templates/base/breadcrumb.html
{%load static%}
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="{%url 'home'%}">Home</a></li>
              <li class="breadcrumb-item active">Dashboard </li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    {%block breadcrumb%}
    {%endblock%}

templates/base/footer.html
<footer class="main-footer">
    <strong>Copyright &copy; 2020 <a href="">Mier Pamoja</a>.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
    </div>
  </footer>

templates/base/header.html
{%load static%}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Mier Pamoja School Management System | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="{%static "plugins/fontawesome-free/css/all.min.css" %}">
    <!-- Ionicons -->
    <link rel="stylesheet" href="{%static "https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" %}">
    <!-- Tempusdominus Bbootstrap 4 -->
    <link rel="stylesheet" href="{%static "plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css" %}">
    <!-- iCheck -->
    <link rel="stylesheet" href="{%static "plugins/icheck-bootstrap/icheck-bootstrap.min.css" %}">
    <!-- JQVMap -->
    <link rel="stylesheet" href="{%static "plugins/jqvmap/jqvmap.min.css" %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{%static "dist/css/adminlte.min.css" %}">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="{%static "plugins/overlayScrollbars/css/OverlayScrollbars.min.css" %}">
    <!-- Daterange picker -->
    <link rel="stylesheet" href="{%static "plugins/daterangepicker/daterangepicker.css" %}">
    <!-- summernote -->
    <link rel="stylesheet" href="{%static "plugins/summernote/summernote-bs4.css" %}">
    <!-- Google Font: Didact Gothic -->
    <link href="{%static "https://fonts.googleapis.com/css2?family=Didact+Gothic&display=swap" %}"  rel="stylesheet">

    {%block header%}
    {%endblock%}
  </head>

templates/base/js.html
{%load static%}
<!-- jQuery -->
<script src="{% static "plugins/jquery/jquery.min.js" %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static "plugins/jquery-ui/jquery-ui.min.js" %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static "plugins/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
<!-- ChartJS -->
<script src="{% static "plugins/chart.js/Chart.min.js" %}"></script>
<!-- Sparkline -->
<script src="{% static "plugins/sparklines/sparkline.js" %}"></script>
<!-- JQVMap -->
<script src="{% static "plugins/jqvmap/jquery.vmap.min.js" %}"></script>
<script src="{% static "plugins/jqvmap/maps/jquery.vmap.usa.js" %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static "plugins/jquery-knob/jquery.knob.min.js" %}"></script>
<!-- daterangepicker -->
<script src="{% static "plugins/moment/moment.min.js" %}"></script>
<script src="{% static "plugins/daterangepicker/daterangepicker.js" %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static "plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js" %}"></script>
<!-- Summernote -->
<script src="{% static "plugins/summernote/summernote-bs4.min.js" %}"></script>
<!-- overlayScrollbars -->
<script src="{% static "plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js" %}"></script>
<!-- AdminLTE App -->
<script src="{% static "dist/js/adminlte.js" %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static "dist/js/pages/dashboard.js" %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static "dist/js/demo.js" %}"></script>

{%block script%}

{%endblock%}

templates/base/navbar.html
{%load static%}
<style>
  .hello-msg{
    font-size: 15px;
    color: #fff;
    margin-right: 20px;
  }
</style>
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-primary navbar-dark">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'home'%}" class="nav-link">Home</a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'home'%}" class="nav-link">Contact</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>
    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
      
      
    </ul>
    
  <span class="hello-msg">Hello, {{request.user}}</span>
  <span ><a  class="hello-msg" href="{% url 'logout' %}">Logout</a></span>

    
    {%block navbar%}
    {%endblock%}
  </nav>
  <!-- /.navbar -->

templates/base/sidebar.html
{%load static%}
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="{%url 'home'%}" class="brand-link">
      <img src="{%static "dist/img/AdminLTELogo.png" %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
           style="opacity: .8">
      <span class="brand-text font-weight-light">Mier Pamoja Admin</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="{%static "dist/img/avatar3.png"  %}" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Ivy Mboya</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills  nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
          <li class="nav-item has-treeview menu-closed">
            <a href="{%url 'home'%}" class="nav-link ">
              <i class="nav-icon fa fa-home  "></i>
              <p>Home
              </p>
            </a>
          </li>
          <!--Student Section START-->
          <li class="nav-item has-treeview menu-closed">
            <a href="#" class="nav-link ">
              <i class="nav-icon fa fa-graduation-cap "></i>
              <p>
               Students
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{%url 'student:student-registration' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Student Registration</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%url 'student:student-list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Student List</p>
                </a>
              </li>
            </ul>
          </li>
          <!--Student section END-->


          <!-- Teacher section START-->
          <li class="nav-item has-treeview menu-closed">
            <a href="#" class="nav-link ">
              <i class="nav-icon fa fa-user "></i>
              <p>
                Teachers
                <i class="right fas fa-angle-left"></i>
              </p>
            </a> <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{%url 'teacher:teacher-registration'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Teacher Registration</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%url 'teacher:teacher-list'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Teacher List</p>
                </a>
              </li>
            </ul>
          </li>
          <!--Teacher Section END-->

          <!--Class Section START-->
          <li class="nav-item has-treeview menu-closed">
            <a href="#" class="nav-link ">
              <i class="nav-icon fa fa-building "></i>
              <p>
                Class
                <i class="right fas fa-angle-left"></i>
              </p>
            </a><ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{%url 'academic:class-registration'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Class Registration</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%url 'academic:class-list'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Class List</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%url 'academic:create-class'%}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Create Class</p>
                </a>
              </li>
            </ul>
          </li>
            <!--Class Section END-->
          <li class="nav-item has-treeview menu-closed">
            <a href="#" class="nav-link ">
              <i class="nav-icon fa fa-user "></i>
              <p>
                Parents
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="{%url 'parent:parent-registration' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Parent Registration</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="{%url 'parent:parent-list' %}" class="nav-link">
                  <i class="far fa-circle nav-icon"></i>
                  <p>Parent List</p>
                </a>
              </li>
            </ul>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
  </aside>
  {%block sidebar%}
  
  {%endblock%}