parent/urls.py
"""Defines the url patterns for the parents app
    """

from django.urls import path
from . import views


#url conf
app_name = 'parent'

urlpatterns = [
    
    path('parent-registration/',views.parent_registration ,name='parent-registration'),
    path('profile/<str:parent_name>',views.parent_profile ,name='parent-profile'),
    path('parent-list/',views.parent_list ,name='parent-list'),
    path('edit/<str:parent_name>',views.parent_edit , name ='parent-edit'),
    path('delete/<str:parent_name>',views.parent_delete , name ='parent-delete'),

]

schoolmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_page
from schoolmanagementsystem import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name = 'home'), #home page
    path('',include('administration.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('parent/',include('parent.urls'))
    
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

teacher/urls.py
from django.urls import path

from . import views
app_name = 'teacher'

urlpatterns = [
    path('registration', views.teacher_registration, name='teacher-registration'),
    path('list', views.teacher_list, name='teacher-list'),
    path('profile/<teacher_id>', views.teacher_profile, name='teacher-profile'),
    path('delete/<teacher_id>', views.teacher_delete, name='teacher-delete'),
    path('edit/<teacher_id>', views.teacher_edit, name='teacher-edit'),
]

teacher/models.py
from django.db import models
from academic.models import Department
from administration.models import Designation

# Create your models here.
class JobInfo(models.Model):
    category_choice =(
        ('Government','Government'),
        ('Non-Government','Non-Government')
    )
    category = models.CharField(choices= category_choice , max_length =50)
    joining_date = models.DateField()
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    institute_name = models.CharField(max_length = 100)
    job_designation = models.ForeignKey(Designation ,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.department)
    class Meta():
        verbose_name_plural = 'Job Information'


class TrainingInfo(models.Model):
    """Information about where a teacher trained at

    Args:
        models ([type]): [description]

    Returns:
        [type]: [description]
    """
    institution_name = models.CharField(max_length = 100)
    year = models.IntegerField()
    duration = models.IntegerField()
    location = models.CharField(max_length = 100)

    def __str__(self):
        return self.institution_name
    class Meta():
        verbose_name_plural = 'Training Information'


class ExperienceInfo(models.Model):
    """Provides info on the experience of a particular teacher(TP)

    Args:
        models ([type]): [description]

    Returns:
        [type]: [description]
    """
    institute_name = models.CharField(max_length = 100)
    designation = models.CharField(max_length = 50)
    trainer = models.CharField(max_length = 50)
    def __str__(self):
        return self.institute_name
    class Meta():
        verbose_name_plural ='Experience Information'    

class PersonalInfo(models.Model):
    name = models.CharField(max_length = 100)
    photo = models.ImageField(upload_to = 'teacher_photos/',blank = True ,null= True, default="defaultuser.png")
    date_of_birth = models.DateField()
    gender_status = (
        ('Male','Male'),
        ('Female','Female'),
        ('Other','Other')
        
    )
    gender = models.CharField(max_length = 50,choices = gender_status)
    phone_no = models.CharField(max_length = 10)
    email = models.EmailField(blank = True)
    father_name = models.CharField(max_length = 50)
    mother_name = models.CharField(max_length = 50)
    religion_status = (
        ('Christian','Christian'),
        ('Muslim','Muslim'),
        ('Other','Other')
    )
    religion = models.CharField(max_length =50 ,choices = religion_status)
    marital_status_choice =(
        ('Married','Married'),
        ('Widowed','Widowed'),
        ('Separated','Separated'),
        ('Divorced','Divorced'),
        ('Single','Single')

    )
    marital_status = models.CharField(choices = marital_status_choice,max_length=10)
    experience = models.ForeignKey(ExperienceInfo, on_delete=models.CASCADE ,null = True,blank = True)
    training = models.ForeignKey(TrainingInfo, on_delete=models.CASCADE , null = True)
    job = models.ForeignKey(JobInfo ,on_delete=models.CASCADE , null = True)
    date = models.DateField(auto_now_add=True)
    is_delete = models.BooleanField(default=False)

    def __str__(self):
        
        """Rerutn a string representation of a teacher's name

        Returns:
            [type] -- [description]
        """
        return self.name

    @property
    def get_photo_url(self):
        if self.photo and hasattr(self.photo ,'url'):
            return self.photo.url    
        else:
            return "teacher_photos/defaultuser.png" 

    class Meta:
        verbose_name_plural = 'Personal Information'

teacher/forms.py
from django import forms
from . import models
from academic.models import Department

class PersonalInfoForm(forms.ModelForm):
    class Meta:
        model = models.PersonalInfo
        exclude = {'training', 'job', 'experience'}
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(attrs={'class': 'form-control'}),
            'nationality': forms.Select(attrs={'class': 'form-control'}),
            'religion': forms.Select(attrs={'class': 'form-control'}),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'phone_no': forms.NumberInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'father_name': forms.TextInput(attrs={'class': 'form-control'}),
            'mother_name': forms.TextInput(attrs={'class': 'form-control'}),
            'marital_status': forms.Select(attrs={'class': 'form-control'}),

        }

class TrainingInfoForm(forms.ModelForm):
    class Meta:
        model = models.TrainingInfo
        fields = '__all__'
        widgets = {
            'institution_name': forms.TextInput(attrs={'class': 'form-control'}),
            'year': forms.NumberInput(attrs={'class': 'form-control'}),
            'duration': forms.NumberInput(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'form-control'}),
        }

class JobInfoForm(forms.ModelForm):
    class Meta:
        model = models.JobInfo
        fields = '__all__'
        widgets = {
            'category': forms.Select(attrs={'class': 'form-control'}),
            'joining_date': forms.TextInput(attrs={'class': 'form-control'}),
            'institute_name': forms.TextInput(attrs={'class': 'form-control'}),
            'job_designation': forms.Select(attrs={'class': 'form-control'}),
            'department': forms.Select(attrs={'class': 'form-control'}),
        }

class ExperienceInfoForm(forms.ModelForm):
    class Meta:
        model = models.ExperienceInfo
        fields = '__all__'
        widgets = {
            'institute_name': forms.TextInput(attrs={'class': 'form-control'}),
            'designation': forms.TextInput(attrs={'class': 'form-control'}),
            'trainer': forms.TextInput(attrs={'class': 'form-control'}),
        }

class AddDesignationForm(forms.ModelForm):
    class Meta:
        model = models.Designation
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
        }

teacher/views.py
from django.shortcuts import render, redirect
from . import forms
from . models import *




def teacher_registration(request):
    form = forms.PersonalInfoForm()
    training_form = forms.TrainingInfoForm()
    job_form = forms.JobInfoForm()
    experience_form = forms.ExperienceInfoForm()
    if request.method == 'POST':
        form = forms.PersonalInfoForm(request.POST, request.FILES)
        training_form = forms.TrainingInfoForm(request.POST)
        job_form = forms.JobInfoForm(request.POST)
        experience_form = forms.ExperienceInfoForm(request.POST)
        if form.is_valid() and training_form.is_valid() and job_form.is_valid() and experience_form.is_valid():
            training_info = training_form.save()
            job_info = job_form.save()
            experience_info = experience_form.save()
            personal_info = form.save(commit=False)
            personal_info.training = training_info
            personal_info.job = job_info
            personal_info.experience = experience_info
            personal_info.save()
            return redirect('teacher:teacher-list')

    context = {
        'form': form,
        'training_form': training_form,
        'job_form': job_form,
        'experience_form': experience_form
    }
    return render(request, 'teacher/teacher-registration.html', context)




def teacher_list(request):
    teacher = PersonalInfo.objects.all()
    context = {'teacher': teacher}
    return render(request, 'teacher/teacher-list.html', context)


def teacher_profile(request, teacher_id):
    teacher = PersonalInfo.objects.get(id=teacher_id)
    context = {
        'teacher': teacher
    }
    return render(request, 'teacher/teacher-profile.html', context)



def teacher_delete(request, teacher_id):
    teacher = PersonalInfo.objects.get(id=teacher_id)
    teacher.is_delete = True
    teacher.save()
    return redirect('teacher:teacher-list')



def teacher_edit(request, teacher_id):
    teacher = PersonalInfo.objects.get(id=teacher_id)
    form = forms.PersonalInfoForm(instance=teacher)
    training_form = forms.TrainingInfoForm(instance=teacher.training)
    job_form = forms.JobInfoForm(instance=teacher.job)
    experience_form = forms.ExperienceInfoForm(instance=teacher.experience)
    if request.method == 'POST':
        form = forms.PersonalInfoForm(request.POST, request.FILES, instance=teacher)
        training_form = forms.TrainingInfoForm(request.POST, instance=teacher.training)
        job_form = forms.JobInfoForm(request.POST, instance=teacher.job)
        experience_form = forms.ExperienceInfoForm(request.POST, instance=teacher.experience)
        if form.is_valid() and training_form.is_valid() and job_form.is_valid() and experience_form.is_valid():
            training_info = training_form.save()
            job_info = job_form.save()
            experience_info = experience_form.save()
            personal_info = form.save(commit=False)
            personal_info.training = training_info
            personal_info.job = job_info
            personal_info.experience = experience_info
            personal_info.save()
            return redirect('teacher:teacher-list')
    context = {
        'form': form,
        'training_form': training_form,
        'job_form': job_form,
        'experience_form': experience_form
    }
    return render(request, 'teacher/teacher-edit.html', context)
    

templates/teacher/teacher-edit.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<h2>Teacher Registration Form</h2>
<!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Personal Information</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action=""enctype="multipart/form-data">
              <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                
              </div>
              <div class="card card-primary">
                
              <div class="card-header">
                <h3 class="card-title">Training Information</h3>
              </div>
              <div class="card-body">
                {% csrf_token %}
                {{ training_form.as_p }}
                
              </div>
              
              <div class="card-header">
                <h3 class="card-title">Job Information</h3>
              </div>
              <div class="card-body">
                {% csrf_token %}
                {{ job_form.as_p }}
                
              </div>
              <div class="card-header">
                <h3 class="card-title">Experience Information</h3>
              </div>
              <div class="card-body">
                {% csrf_token %}
                {{ experience_form.as_p }}
                
              </div>
              
              

                
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Save Teacher</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
  
{%endblock%}

templates/teacher/teacher-list.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Teacher Tables</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        {%if teacher%}
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Gender</th>
                <th>Email</th>
                <th>Date</th>
      
              </tr>
            </thead>
            <tbody>
              {%for teacher in teacher%}
              <tr role="row" >
                
                <td>{{forloop.counter}}</td>
                <td>{{teacher.name}}</td>
                <td>{{teacher.gender}}</td>
                <td>{{teacher.email}}</td>
                <td>{{teacher.date}}</td>
                <td>
                    <a class="btn btn-info" href="{% url 'teacher:teacher-profile' teacher.id %}">
                        <i class="fa fa-search-plus"></i>
                    </a>

                  
                    <a class="btn btn-success" href="{%url 'teacher:teacher-edit' teacher.id %}">
                      <i class="fa fa-edit"></i>
                    </a> 

                 
                  <a class="btn btn-danger" href="{%url  'teacher:teacher-delete' teacher.id %}" >
                    <i class="fa fa-trash"></i>
                    </a>
                </td>
              </tr>
              
                {%endfor%}
    
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    {%else%}
    <div class="card-body">
      <h2>No Teacher Found</h2>
    </div>
    {%endif%}
  </div>
  <!-- /.row -->
{%endblock%}

templates/teacher/teacher-profile.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
  <div class="card">
    
    <div class="card-header">
      <div class="row">
        {%if teacher.photo %}
        <img style="height:200px; width:200px; border-radius:50%; margin:auto ;background-size:cover"  src="{{ teacher.get_photo_url }}" alt="Photo">
      {% else %}
      <img style="height:200px; width:200px; border-radius:50%; margin:auto ;background-size:cover"  src="{%static 'images/default.jpg'%}" alt="Photo">
        {% endif %}
      </div>
    </div>
    
    <div class="card-body">

      <div class="personal_information">
        <div class="row">
          <h2 class="mx-auto">Personal Information</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Name                    : {{ teacher.name }}</pre>
            <pre>Date of Birth           : {{ teacher.date_of_birth }}</pre>
            <pre>Religion                : {{ teacher.religion }}</pre>
            <pre>Gender                  : {{ teacher.gender }}</pre>
            <pre>Phone No                : {{ teacher.phone_no }}</pre>
            <pre>Email                   : {{ teacher.email }}</pre>
            <pre>Father`s Name           : {{ teacher.father_name }}</pre>
            <pre>Mother`s Name           : {{ teacher.mother_name }}</pre>
            <pre>Marital Status          : {{ teacher.marital_status }}</pre>
            <pre>Training                : {{ teacher.training }}</pre>
            <pre>Job                     : {{ teacher.job }}</pre>
            <pre>Experience              : {{ teacher.experience }}</pre>
          </div>
        </div>
      </div>

      

      

      <div class="emergency_contact_information">
        <div class="row">
          <h2 class="mx-auto">Training Information</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            
            <pre>Year                    : {{ teacher.training.year }}</pre>
            <pre>Duration                : {{ teacher.training.duration }}</pre>
            
          </div>
        </div>
      </div>

      <div class="emergency_contact_information">
        <div class="row">
        <h2 class="mx-auto">Job Information</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Category                : {{ teacher.job.category }}</pre>
            <pre>Joining Date            : {{ teacher.job.joning_date }}</pre>
            <pre>Institute Name          : {{ teacher.job.institute_name }}</pre>
            <pre>Job Designation         : {{ teacher.job.job_designation }}</pre>
            <pre>Department              : {{ teacher.job.department }}</pre>
            
        
          </div>
        </div>
      </div>

      <div class="previous_academic_information">
        <div class="row">
          <h2 class="mx-auto">Experience Information</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Institute Name          : {{ teacher.experience.institute_name }}</pre>
            <pre>Designation             : {{ teacher.experience.designation }}</pre>
            <pre>Trainer                 : {{ teacher.experience.trainer }}</pre>
          </div>
        </div>
      </div>

    </div>
  </div>
{% endblock %}

templates/teacher/teacher-registration.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<h2>Teacher Registration Form</h2>
<!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
               <h3 class="card-title">Personal Information</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{%url 'teacher:teacher-registration'%}"enctype="multipart/form-data">
              <div class="card-body">
                {% csrf_token %}
                {{ form.as_p }}
                
              </div>
              <div class="card card-primary">
                
              <div class="card-header">
                <h3 class="card-title">Training Information</h3>
              </div>
              <div class="card-body">
                {% csrf_token %}
                {{ training_form.as_p }}
                
              </div>
              <div class="card-header">
                <h3 class="card-title">Job Information</h3>
              </div>
              <div class="card-body">
                {% csrf_token %}
                {{ job_form.as_p }}
                
              </div>
              <div class="card-header">
                <h3 class="card-title">Experience Information</h3>
              </div>
              <div class="card-body">
                {% csrf_token %}
                {{ experience_form.as_p }}
                
              </div>
              
                
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
  

{%endblock%}