parent/urls.py
"""Defines the url patterns for the parents app
    """

from django.urls import path
from . import views


#url conf
app_name = 'parent'

urlpatterns = [
    
    path('parent-registration/',views.parent_registration ,name='parent-registration'),
    path('profile/<str:parent_name>',views.parent_profile ,name='parent-profile'),
    path('parent-list/',views.parent_list ,name='parent-list'),
    path('edit/<str:parent_name>',views.parent_edit , name ='parent-edit'),
    path('delete/<str:parent_name>',views.parent_delete , name ='parent-delete'),

]

schoolmanagementsystem/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import home_page
from schoolmanagementsystem import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_page, name = 'home'), #home page
    path('',include('administration.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
    path('academic/', include('academic.urls')),
    path('parent/',include('parent.urls'))
    
]
if settings.DEBUG is True:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

parent/models.py
from django.db import models


# Create your models here.
class Personalinfo(models.Model):
    """Provides personal information about each and every parent

    Args:
        models ([type]): [description]

    Returns:
        [type]: [description]
    """
    name = models.CharField(max_length = 100)
    photo = models.ImageField(upload_to = 'parent-photos/',blank = True,null =True)
    date_of_birth = models.DateField()
    gender_choices =(
        ('male','Male'),
        ('female','Female'),
        ('other','Other')
        
    )
    gender = models.CharField(choices = gender_choices,max_length=10)
    phone_no = models.CharField(max_length = 10)
    email = models.EmailField(blank = True)
    religion_choice =(
        ('christian','Christian'),
        ('muslim','Muslim'),
        ('other','Other')
    )
    religion = models.CharField(choices = religion_choice,max_length = 50)
    RELATIONSHIP =[
        ('Mother','Mother'),
        ('Father','Father'),
        ('Guardian','Guardian')
    ]
    relationship_to_student = models.CharField(max_length = 50 ,choices=RELATIONSHIP, default='Mother')
    parent_to = models.CharField(max_length =100)
    is_delete = models.BooleanField(default=False)
    

    def __str__(self):
        
        """Return a string representation of a parent's name

        Returns:
            [type] -- [description]
        """
        return self.name

    @property
    def get_photo_url(self):
        if self.photo and hasattr(self.photo ,'url'):
            return self.photo.url    
       
    

    class Meta:
        verbose_name_plural = 'Personal Information'

parent/forms.py
from django import forms
from .models import *




class ParentPersonalInfoForm(forms.ModelForm):
    class Meta:
        model = Personalinfo
        exclude =['is_delete']
        widgets = {
            'name' : forms.TextInput(attrs={'class':'form-control'}),
            'photo' : forms.ClearableFileInput(attrs={'class':'form-control'}),
            'gender' : forms.Select(attrs={'class':'form-control'}),
            'phone_no' : forms.TextInput(attrs={'class':'form-control'}),
            'email' : forms.TextInput(attrs={'class':'form-control'}),
            'religion' : forms.Select(attrs={'class':'form-control'}),
            'relationship_to_student' : forms.Select(attrs={'class':'form-control'}),
            'parent_to': forms.TextInput(attrs={'class':'form-control'}),

        }

parent/views.py
# Create your views here.
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import *
from .forms import *

# Create your views here.

def parent_registration(request):
    """A parent registration form that is sent back to the database when it is valid

    Args:
        request ([type]): [description]

    Returns:
        [type]: [description]
    """
    personal_info_form = ParentPersonalInfoForm(request.POST)
    

    if request.method == 'POST':

        if personal_info_form.is_valid():
            personal_info_form.save()
            return redirect('parent:parent-list')

    context ={
        'personal_info_form':personal_info_form,
    }
    
    return render(request, 'parent/parent_registration.html',context)

def parent_profile(request,parent_name):
    """Returns a student to their profile page

    Args:
        request ([type]): [description]
        reg_no ([type]): [description]

    Returns:
        [type]: [description]
    """
    parent = Personalinfo.objects.get(name = parent_name)
    context = {'parent':parent}
    return render(request,'parent/parent-profile.html',context)



def parent_list(request):
    """Shows the whole list of parents

    Args:
        request ([type]): [description]

    Returns:
        [type]: [description]
    """
    parents =Personalinfo.objects.filter(is_delete=False).order_by('-id')
    context ={'parents' : parents }
    return render(request,'parent/parent_list.html',context)



def parent_edit(request,parent_name):
    """Edit's the parent registration form and redirects them to the parent list page

    Args:
        request ([type]): [description]
        reg_no ([type]): [description]

    Returns:
        [type]: [description]
    """
#GET METHOD = BLANK FORM
    parent = Personalinfo.objects.get(name=parent_name)
    personal_info_form = ParentPersonalInfoForm(instance=parent)
    
#POST METHOD = FILL IT WITH DATA
    if request.method == 'POST':
        personal_info_form = ParentPersonalInfoForm(request.POST,request.FILES,instance=parent)
        

        if personal_info_form.is_valid():
            s1=personal_info_form.save()

            return redirect('parent:parent-list')
            
    context ={
        'personal_info_form':personal_info_form,
    }
    
    return render(request,'parent/parent-edit.html',context)




def parent_delete(request,parent_name):
    """Deletes a parent

    Args:
        request ([type]): [description]
        reg_no ([type]): [description]

    Returns:
        [type]: [description]
    """
    parent = Personalinfo.objects.get(name = parent_name)
    parent.is_delete = True
    parent.save()
    return redirect('parent:parent-list')

templates/parent/parent-edit.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<h2>Parent Registration Form</h2>
<!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Personal Information</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action=""  enctype="multipart/form-data">
              <div class="card-body">
                {% csrf_token %}
                {{ personal_info_form.as_p }}
                
              </div>
              <div class="card card-primary">
                
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Save Parent</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
  
{%endblock%}

templates/parent/parent-profile.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
  <div class="card">
    
    <div class="card-header">
      <div class="row">
        {%if parent.photo %}
        <img style="height:200px; width:200px; border-radius:50%; margin:auto ;background-size:cover"  src="{{ parent.get_photo_url}}" alt="Photo">
      {% else %}
      <img style="height:200px; width:200px; border-radius:50%; margin:auto ;background-size:cover"  src="{%static 'images/default.jpg'%}" alt="Photo">
        {% endif %}
      </div>
    </div>
    
    <div class="card-body">

      <div class="personal_information">
        <div class="row">
          <h2 class="mx-auto">Personal Information</h2>
        </div>
        <hr>
        <div class="row">
          <div style="font-size:24px; margin-left: 30px">
            <pre>Name                        :  {{parent.name}}</pre>
            <pre>Date of birth               :  {{parent.date_of_birth}} </pre>
            <pre>Gender                      :  {{parent.gender}}</pre>
            <pre>Phone number                :  {{parent.phone_no}}</pre>
            <pre>Email                       :  {{parent.email}}</pre>
            <pre>Religion                    :  {{parent.religion}}</pre>
            <pre>Relationship to student     :  {{parent.relationship_to_student}}</pre>
            <pre>Parent to                   :  {{parent.parent_to}}</pre>
          </div>
        </div>
      </div>

      

      

    </div>
  </div>
{% endblock %}

templates/parent/parent_list.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-header">
          <h3 class="card-title">Parent Tables</h3>

          <div class="card-tools">
            <div class="input-group input-group-sm" style="width: 150px;">
              <input type="text" name="table_search" class="form-control float-right" placeholder="Search">

              <div class="input-group-append">
                <button type="submit" class="btn btn-default"><i class="fas fa-search"></i></button>
              </div>
            </div>
          </div>
        </div>
        <!-- /.card-header -->
        {%if parents%}
        <div class="card-body table-responsive p-0">
          <table class="table table-hover text-nowrap">
            <thead>
              <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Phone Number</th>
                <th>Email</th>
                <th>Parent To</th>
                
              </tr>
            </thead>
            <tbody>
              {%for parent in parents%}
              <tr role="row" >
                
                <td>{{forloop.counter}}</td>
                <td>{{parent.name}}</td>
                <td>{{parent.phone_no}}</td>
                <td>{{parent.email}}</td>
                <td>{{parent.parent_to}}</td>
                
                <td>
                  
                    <a class="btn btn-primary"href="{%url 'parent:parent-profile' parent.name %}">
                      <i class="fa fa-search-plus "></i>
                    </a> 
                  
                  
                    <a class="btn btn-success"href="{%url 'parent:parent-edit' parent.name %}">
                      <i class="fa fa-edit"></i>
                    </a>
                
                  <a class="btn btn-danger" href="{%url 'parent:parent-delete' parent.name %}" >
                    <i class="fa fa-trash"></i>
                    </a>
                   
                </td>
              </tr>
              
                {%endfor%}
    
            </tbody>
          </table>
        </div>
        <!-- /.card-body -->
      </div>
      <!-- /.card -->
    </div>
    {%else%}
    <div class="card-body">
      <h2>No Parent Found</h2>
    </div>
    {%endif%}
  </div>
  <!-- /.row -->
{%endblock%}

templates/parent/parent_registration.html
{%extends 'base/base.html'%}
{%load static%}
{%block content%}
<h2>Parent Registration Form</h2>
<!-- Main content -->
    <div class="container-fluid">
      <div class="row">
        <!-- left column -->
        <div class="col-md-6">
          <!-- general form elements -->
          <div class="card card-primary">
            <div class="card-header">
              <h3 class="card-title">Personal Information</h3>
            </div>
            <!-- /.card-header -->
            <!-- form start -->
            <form role="form" method="POST" action="{%url 'parent:parent-registration'%}">
              <div class="card-body">
                
                {% csrf_token %}
                {{ personal_info_form.as_p }}
                
              </div>
              <div class="card card-primary">
                
              <!-- /.card-body -->

              <div class="card-footer">
                <button type="submit" class="btn btn-primary">Submit</button>
              </div>
            </form>
          </div>
          <!-- /.card -->
  

{%endblock%}